version: "3"

services:
  api:
    build: ./routes-api
    entrypoint: ./.docker/entrypoint.sh
    container_name: desafio-02-routes-api
    ports:
      - 3000:3000
    volumes:
      - ./routes-api:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  app:
    build: ./routes-front
    entrypoint: ./.docker/entrypoint.sh
    container_name: desafio-02-routes-front
    ports:
      - 3001:3000
    volumes:
      - ./routes-front:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - api
