version: '3'

services:
  api:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: desafio-02-routes-api
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
