version: "3"

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: desafio-02-routes-front
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
